version: '3.2'
volumes:
    prometheus_data: {}
services:
    prometheus:
        image: prom/prometheus:latest
        volumes:
            - prometheus_data:/prometheus
            - ./prometheus/:/etc/prometheus/
        command:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
        ports:
            - 9090:9090
        restart: always
    alertmanager-bot:
        command:
        - --alertmanager.url=http://alertmanager:9093
        - --log.level=info
        - --store=bolt
        - --bolt.path=/data/bot.db
        environment:
          TELEGRAM_ADMIN: "429106594"
          TELEGRAM_TOKEN: 1928706029:AAFtDb0fuLzpN0y2gr8c523YGFHwPBiiz4w
        hostname: alertmanager-bot
        image: metalmatze/alertmanager-bot:latest
        ports:
        - 8080:8080
        restart: always
        volumes:
        - ./data:/data

    alertmanager:
      image: prom/alertmanager:latest
      ports:
        - 9093:9093
      hostname: alertmanager
      volumes:
        - ./alertmanager/:/etc/alertmanager/
      restart: always
      command:
        - '--config.file=/etc/alertmanager/config.yml'
        - '--storage.path=/etc/alertmanager/'
    node-exporter:
        image: prom/node-exporter
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        hostname: monitoring
        command:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points
            - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
        ports:
            - 9100:9100
        restart: always

    grafana:
      image: grafana/grafana
      depends_on:
        - prometheus
      ports:
        - 3000:3000
      restart: always

    blackbox-exporter:
      image: prom/blackbox-exporter
      hostname: blackbox-exporter
      ports:
        - 9115:9115
      restart: always
      volumes:
        - ./blackbox:/blackbox
      command: --config.file=/blackbox/config.yml